# Generated by Django 3.2.7 on 2022-01-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tama',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
